Merged PR 712003: Fallback to BuildXLReader based serialization in case of an error with the sp...
Very rarely we're getting `ArgumentOutOfRangeException` when deserializaing events from LLS.

This PR adds the fallback logic to use the old BuildXLReader-based logic and trace at least portion of the message to figure out what's the reason of the serialization error.

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at byte[] BuildXL.Cache.MemoizationStore.Interfaces.Sessions.ContentHashList.ReadNullableArray(ref SpanReader reader) in \.\Public\Src\Cache\MemoizationStore\Interfaces\Sessions\ContentHashList.cs:line 326
   at ContentHashList BuildXL.Cache.MemoizationStore.Interfaces.Sessions.ContentHashList.Deserialize(ref SpanReader reader) in \.\Public\Src\Cache\MemoizationStore\Interfaces\Sessions\ContentHashList.cs:line 267
   at ContentHashListWithDeterminism BuildXL.Cache.MemoizationStore.Interfaces.Sessions.ContentHashListWithDeterminism.Deserialize(ref SpanReader reader) in \.\Public\Src\Cache\MemoizationStore\Interfaces\Sessions\ContentHashListWithDeterminism.cs:line 64
   at MetadataEntry BuildXL.Cache.ContentStore.Distributed.NuCache.MetadataEntry.Deserialize(ref SpanReader reader) in \.\Public\Src\Cache\ContentStore\Distributed\NuCache\MetadataEntry.cs:line 47
   at UpdateMetadataEntryEventData BuildXL.Cache.ContentStore.Distributed.NuCache.EventStreaming.UpdateMetadataEntryEventData.Deserialize(ref SpanReader reader, MachineId sender) in \.\Public\Src\Cache\ContentStore\Distributed\NuCache\EventStreaming\ContentLocationEventData.cs:line 406
   at ContentLocationEventData BuildXL.Cache.ContentStore.Distributed.NuCache.EventStreaming.ContentLocationEventData.Deserialize(ref SpanReader reader, DateTime eventTimeUtc) in \.\Public\Src\Cache\ContentStore\Distributed\NuCache\EventStreaming\ContentLocationEventData.cs:line 113
   at IReadOnlyList<ContentLocationEventData> BuildXL.Cache.ContentStore.Distributed.NuCache.EventStreaming.ContentLocationEventDataSerializer.DeserializeEventsWithSpan(EventData message, DateTime? eventTimeUtc)+(bool _) => { } in \.\Public\Src\Cache\ContentStore\Distributed\NuCache\EventStreaming\ContentLocationEventDataSerializer.cs:line 616
   at T BuildXL.Cache.ContentStore.Distributed.NuCache.EventStreaming.ContentLocationEventDataSerializer.SynchronizeIfNeeded<T>(Func<bool, T> func) in \.\Public\Src\Cache\ContentStore\Distributed\NuCache\EventStreaming\ContentLocationEventDataSerializer.cs:line 669
   at async Task BuildXL.Cache.ContentStore.Distributed.NuCache.EventStreaming.EventHubContentLocationEventStore.ProcessEventsCoreAsync(ProcessEventsInput input, ContentLocationEventDataSerializer eventDataSerializer)+(?) => { }
   at async Task<T> BuildXL.Cache.ContentStore.Tracing.Internal.PerformOperationBuilderBase<TResult, TBuilder>.RunOperationAndConvertExceptionToErrorAsync<T>(Func<Task<T>> operation, StopwatchSlim stopwatch) in \.\Public\Src\Cache\ContentStore\Library\Tracing\OperationContextExtensions.cs:line 299
```