Merged PR 670161: RpcException is swallowed
RpcException is thrown by grpc.net tasks when some of the new features are used (keepalive, load-balancer). The grpc.net is fixing some of them, but it will probably take some time.

 One example:
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Status(StatusCode="DeadlineExceeded", Detail="Deadline Exceeded"))
 ---> Grpc.Core.RpcException: Status(StatusCode="DeadlineExceeded", Detail="Deadline Exceeded")
   --- End of inner exception stack trace ---