Merged PR 827086: Fix crash when measuring the ram size for dynamic VMs
One particular developer hits the following crash:

System.Diagnostics.ContractsLight.ContractException: Precondition failed (value > 0)
	at \.\Public\Src\Pips\Dll\Operations\ProcessSemaphoreInfo.cs:37
   at void System.Diagnostics.ContractsLight.ContractRuntimeHelper.ReportFailure(ContractFailureKind kind, string msg, string conditionTxt, Provenance provenance) in C:/Sources/GitHub/RuntimeContracts/src/RuntimeContracts/ContractRuntimeHelper.cs:line 20
   at void System.Diagnostics.ContractsLight.Contract.Requires(bool condition, string userMessage, string conditionText, string path, int lineNumber) in C:/Sources/GitHub/RuntimeContracts/src/RuntimeContracts/Contract.cs:line 55
   at new BuildXL.Pips.Operations.ProcessSemaphoreInfo(StringId name, int value, int limit) in \.\Public\Src\Pips\Dll\Operations\ProcessSemaphoreInfo.cs:line 37
   at void BuildXL.Scheduler.Distribution.Worker.UpdateMachineSemaphores(int? engineRamMb, int? engineCpuUsage) in \.\Public\Src\Engine\Scheduler\Distribution\Worker.cs:line 663
   at void BuildXL.Scheduler.Distribution.Worker.UpdatePerfInfo(LoggingContext loggingContext, int? currentTotalRamMb, int? machineAvailableRamMb, int? engineRamMb, int? engineCpuUsage, int? machineCpuUsage) in \.\Public\Src\Engine\Scheduler\Distribution\Worker.cs:line 878
   at void BuildXL.Scheduler.Scheduler.UpdateStatus(bool overwriteable, int expectedCallbackFrequency) in \.\Public\Src\Engine\Scheduler\Scheduler.cs:line 2670
   at bool BuildXL.Engine.EngineSchedule.ExecuteScheduledPips(LoggingContext loggingContext, WorkerService workerService)+() => { } in \.\Public\Src\Engine\Dll\EngineSchedule.cs:line 1475
   at void BuildXL.Utilities.Core.CancellableTimedAction.Loop(Action callback, int intervalMs, CancellationToken token) in \.\Public\Src\Utilities\Utilities.Core\CancellableTimedAction.cs:line 81
   at BuildXL.Utilities.Core.CancellableTimedAction(Action callback, int intervalMs, string name)+() => { } in \.\Public\Src\Utilities\Utilities.Core\CancellableTimedAction.cs:line 29