Merged PR 526876: Specify error regex for csc.exe
We now have csc.exe running with a few analyzers that produce info messages. You never see these until you hit a compile error, at which point your error is in a huge blob of red because we just repeat the entire output stream as the error.

This change specifies an error regex so just csc.exe's error is printed to the console

Old:
```
F:\src\BuildXL.Internal.mpysson\Public\Src\App\Bxl\BuildXLApp.cs(1321,21): error CS1501: No overload for method 'ConfigureTrackingListener' takes 1 arguments
F:\src\BuildXL.Internal.mpysson\Public\Src\App\Bxl\AzureDevOpsListener.cs(53,13): info RA003: Use simplified null check.
F:\src\BuildXL.Internal.mpysson\Public\Src\App\Bxl\AzureDevOpsListener.cs(54,13): info RA003: Use simplified null check.
F:\src\BuildXL.Internal.mpysson\Public\Src\App\Bxl\ConsoleEventListener.cs(193,13): info RA003: Use simplified null check.
```
...many more lines

New:
```
F:\src\BuildXL.Internal.mpysson\Public\Src\App\Bxl\BuildXLApp.cs(1321,21): error CS1501: No overload for method 'ConfigureTrackingListener' takes 1 arguments
```