[.NET Core] EventWaitHandle.TryOpenExisting with Synchronize rights only (#355)
.NET Core does not have a method for opening an existing EventWaitHandle with access rights explicitly specified, i.e., EventWaitHandle doesn't have a static method like

    bool TryOpenExisting(string name, EventWaitHandleRights rights, out EventWaitHandle result)

Both .NET Core and .NET Framework do have

    bool TryOpenExisting(string name, out EventWaitHandle result)

which implicitly requests the EventWaitHandleRights.Synchronize | EventWaitHandleRights.Modify rights (see EventWaitHandle.OpenExistingWorker).

Currently, when we create an EventWaitHandle, we only allow EventWaitHandleRights.Synchronize. Consequently, if we try to open that same event handle from a .NET Core process, we get an access denied error:

    System.UnauthorizedAccessException: Access to the path 'Global\ContentServerReadyEvent' is denied.

This PR:

  - implements a workaround where a lower-level OpenEventW (from "kernel32.dll") is p-invoked to achieve the existing behavior of opening an existing EventWaitHandle with Synchronize rights only.

AB#1541060