Merged PR 526300: Revert "Merged PR 525531: Auto enable dev log outside of Cloudbuild"
Revert "Merged PR 525531: Auto enable dev log outside of Cloudbuild"

This reverts commit c94d304db80dd9cd4b116c1cfc03b5a15ff26b5a.

The commit somehow broke server mode in Office dev builds.

```
E:\OffTest\dev\graph>obuild
E:\OffTest\Build\OfficeNugetInit\gen\.versionless\Office.StaticGraph\lib\net45\dbuild.exe --BuildCWD --WriteObuildLogs --PrintObuildTimes --SendObuildTelemetry --Platforms x64 --Flavors debug --FileOpsToRun pescan
Success: Task 'Enlist Build Prep' completed in 0:00:00.049
Starting task 'Domino Enlist Build' started [ 03:50:59 PM ]
Terminating BuildXL client process because communication with the server has been lost: Error while reading data from server process. Server will be redeployed in subsequent invocation. Inner exception reason: Unable to read beyond the end of the stream.
Error: Unable to complete task 'Domino Enlist Build'.  Exit code: 50
------------------------------------------------------------------------------
OBUILD: Logs     at "E:\OffTest\Logs\obuild"
OBUILD: Started  at Fri Dec 27 15:50:58 2019
OBUILD: Finished at Fri Dec 27 15:51:03 2019
OBUILD: Total Time to build was 4.7 Seconds
------------------------------------------------------------------------------
Error: Main Exit Code: 50, Exit Action Exit Code: Failed, Final Exit Code: 50
```