Merged PR 560041: Use PerformOperation to avoid startup failures if CaSaaSRunning.txt is locked
Use PerformOperation to avoid startup failures if CaSaaSRunning.txt is locked

This fix should avoid startup failures like this one:

```
System.IO.IOException: The process cannot access the file 'D:\dbs\Cache\ContentAddressableStore\CaSaaSRunning.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at BuildXL.Cache.ContentStore.FileSystem.PassThroughFileSystem.ReadAllBytes(AbsolutePath path) in \.\Public\Src\Cache\ContentStore\Library\FileSystem\PassThroughFileSystem.cs:line 100
   at BuildXL.Cache.Host.Service.ServiceOfflineDurationTracker.GetOfflineDuration() in \.\Public\Src\Cache\DistributedCache.Host\Service\ServiceOfflineDurationTracker.cs:line 84
   at BuildXL.Cache.Host.Service.DistributedCacheServiceFacade.ReportServiceStarted(Context context, IDistributedCacheServiceHost host, Result`1 trackerResult, TimeSpan startupDuration) in \.\Public\Src\Cache\DistributedCache.Host\Service\DistributedCacheServiceFacade.cs:line 134
   at BuildXL.Cache.Host.Service.DistributedCacheServiceFacade.<RunAsync>d__0.MoveNext() in \.\Public\Src\Cache\DistributedCache.Host\Service\DistributedCacheServiceFacade.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at BuildXL.Cache.Host.Service.DistributedCacheServiceFacade.<RunAsync>d__0.MoveNext() in \.\Public\Src\Cache\DistributedCache.Host\Service\DistributedCacheServiceFacade.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DBS.ContentAddressableStore.ContentAddressableStoreService.WaitForServiceExit() in d:\dbs\el\cb_m\private\Services\ContentAddressableStore\ContentAddressableStoreService.cs:line 165
```